services:
  portainer:
    image: portainer/portainer-ce:2.22.0
    
    container_name: portainer

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: {}
