# docker-compose.yml
version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.20.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    container_name: portainer
volumes:
  portainer_data: {}