version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:2024.10.0
    tty: true
    stdin_open: true

    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"
      MODE: "survival"
      VERSION: "1.21"
      MOTD: "Your super-cool, super-kube, minecraft server"
      ALLOW_FLIGHT: "TRUE"
      TYPE: "FABRIC"
      OPS: ""

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
